github: ezitisitis
buy_me_a_coffee: ezitisitis
custom:
  - https://etherscan.io/address/0x1732b7b8d490e5114754702E9bF07dE61AA63691
  - https://mempool.space/address/bc1qwczllcjeen7yzpj50dn950t6m82ryggf9pkhas
  - https://tronscan.org/#/address/TJQK7UQVNGwavkCXmitUHVCFcRfMdZQAHs
